//! Abstract Syntax Tree (AST) definitions for the T4 programming language
//!
//! This module contains all the AST node types that represent the parsed T4 source code.
//! The AST is designed to be:
//! - Type-safe with full type information
//! - Serializable for debugging and tooling
//! - Memory efficient with interned strings
//! - Source location aware for error reporting

use serde::{Deserialize, Serialize};
use std::fmt;
// Simple symbol type to replace string_interner::Sym for now
pub type Sym = u32;

/// Source location information for AST nodes
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceLocation {
    /// Starting line number (1-based)
    pub start_line: usize,
    /// Starting column (1-based)
    pub start_column: usize,
    /// Ending line number (1-based)
    pub end_line: usize,
    /// Ending column (1-based)
    pub end_column: usize,
    /// File path or identifier
    pub file: Sym,
}

/// Span of source text
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceSpan {
    pub location: SourceLocation,
}

/// AST node with source location
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Spanned<T> {
    pub node: T,
    pub span: SourceSpan,
}

impl<T> Spanned<T> {
    pub fn new(node: T, span: SourceSpan) -> Self {
        Self { node, span }
    }

    pub fn map<U, F>(self, f: F) -> Spanned<U>
    where
        F: FnOnce(T) -> U,
    {
        Spanned {
            node: f(self.node),
            span: self.span,
        }
    }
}

// Re-export commonly used types
// pub use crate::generated::t4parser::*; // TODO: Generated by ANTLR build process

// Import generated AST nodes
pub mod nodes {
    // These will be generated by ANTLR
    // TODO: Fix when ANTLR build process is integrated
    // include!(concat!(env!("OUT_DIR"), "/t4.ast.nodes.rs"));
}

// Type aliases for convenience
pub type SpannedExpr = Spanned<Expression>;
pub type SpannedStmt = Spanned<Statement>;
pub type SpannedDecl = Spanned<Declaration>;
pub type SpannedType = Spanned<Type>;
pub type SpannedPattern = Spanned<Pattern>;
pub type SpannedIdent = Spanned<Identifier>;

/// Identifier with interning
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Identifier {
    pub name: Sym,
    pub span: SourceSpan,
}

impl Identifier {
    pub fn new(name: Sym, span: SourceSpan) -> Self {
        Self { name, span }
    }
}

impl fmt::Display for Identifier {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.name)
    }
}

/// Type information for expressions and variables
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Type {
    // Basic types
    Int8,
    Int16,
    Int32,
    Int64,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    Float32,
    Float64,
    Bool,
    String,
    Bytes,

    // Cryptographic types
    Key(AlgorithmType),
    Secret(Box<Type>),
    PublicKey(AlgorithmType),
    PrivateKey(AlgorithmType),
    Signature(AlgorithmType),
    Ciphertext(AlgorithmType),
    Plaintext(AlgorithmType),
    Hash(AlgorithmType),
    Nonce,
    Salt,

    // Complex types
    Tuple(Vec<Type>),
    Array(Box<Type>, usize),
    Slice(Box<Type>),
    Reference(Box<Type>),
    MutableReference(Box<Type>),
    Function {
        params: Vec<Type>,
        return_type: Box<Type>,
    },
    Generic {
        base: Box<Type>,
        args: Vec<Type>,
    },
    Path {
        module: Option<Vec<Identifier>>,
        name: Identifier,
        args: Vec<Type>,
    },

    // Special types
    Unit,
    Never,
    Infer,
}

/// Algorithm types for cryptographic operations
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlgorithmType {
    // Symmetric encryption
    Aes256,
    ChaCha20,

    // Post-quantum cryptography
    Kyber1024,
    Kyber768,
    Kyber512,
    Dilithium3,
    Dilithium2,
    Dilithium5,
    Falcon512,
    Falcon1024,

    // Classical cryptography
    Ed25519,
    SecP256r1,
    SecP384r1,
    SecP521r1,
    Rsa2048,
    Rsa3072,
    Rsa4096,

    // Homomorphic encryption
    Ckks,
    Bfv,
    Bgv,

    // Zero-knowledge proofs
    Groth16,
    Bulletproofs,
    Stark,
    Plonk,

    // Hash functions
    Sha3_256,
    Sha3_512,
    Blake2b,
    Shake256,

    // Custom algorithm
    Custom(String),
}

impl fmt::Display for AlgorithmType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            AlgorithmType::Aes256 => write!(f, "AES256"),
            AlgorithmType::ChaCha20 => write!(f, "ChaCha20"),
            AlgorithmType::Kyber1024 => write!(f, "Kyber1024"),
            AlgorithmType::Kyber768 => write!(f, "Kyber768"),
            AlgorithmType::Kyber512 => write!(f, "Kyber512"),
            AlgorithmType::Dilithium3 => write!(f, "Dilithium3"),
            AlgorithmType::Dilithium2 => write!(f, "Dilithium2"),
            AlgorithmType::Dilithium5 => write!(f, "Dilithium5"),
            AlgorithmType::Falcon512 => write!(f, "Falcon512"),
            AlgorithmType::Falcon1024 => write!(f, "Falcon1024"),
            AlgorithmType::Ed25519 => write!(f, "Ed25519"),
            AlgorithmType::SecP256r1 => write!(f, "SecP256r1"),
            AlgorithmType::SecP384r1 => write!(f, "SecP384r1"),
            AlgorithmType::SecP521r1 => write!(f, "SecP521r1"),
            AlgorithmType::Rsa2048 => write!(f, "RSA2048"),
            AlgorithmType::Rsa3072 => write!(f, "RSA3072"),
            AlgorithmType::Rsa4096 => write!(f, "RSA4096"),
            AlgorithmType::Ckks => write!(f, "CKKS"),
            AlgorithmType::Bfv => write!(f, "BFV"),
            AlgorithmType::Bgv => write!(f, "BGV"),
            AlgorithmType::Groth16 => write!(f, "Groth16"),
            AlgorithmType::Bulletproofs => write!(f, "Bulletproofs"),
            AlgorithmType::Stark => write!(f, "STARK"),
            AlgorithmType::Plonk => write!(f, "PLONK"),
            AlgorithmType::Sha3_256 => write!(f, "SHA3_256"),
            AlgorithmType::Sha3_512 => write!(f, "SHA3_512"),
            AlgorithmType::Blake2b => write!(f, "BLAKE2b"),
            AlgorithmType::Shake256 => write!(f, "SHAKE256"),
            AlgorithmType::Custom(s) => write!(f, "{}", s),
        }
    }
}

/// Security annotations for functions and types
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SecurityAnnotation {
    ConstantTime,
    CacheResistant,
    SecureMemory,
    VerifyProtocol,
    WipeOnDrop,
    Distributed,
    ThresholdSign,
    VerifySoundness,
    VerifyZeroKnowledge,
    PowerResistant,
}

impl fmt::Display for SecurityAnnotation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SecurityAnnotation::ConstantTime => write!(f, "constant_time"),
            SecurityAnnotation::CacheResistant => write!(f, "cache_resistant"),
            SecurityAnnotation::SecureMemory => write!(f, "secure_memory"),
            SecurityAnnotation::VerifyProtocol => write!(f, "verify_protocol"),
            SecurityAnnotation::WipeOnDrop => write!(f, "wipe_on_drop"),
            SecurityAnnotation::Distributed => write!(f, "distributed"),
            SecurityAnnotation::ThresholdSign => write!(f, "threshold_sign"),
            SecurityAnnotation::VerifySoundness => write!(f, "verify_soundness"),
            SecurityAnnotation::VerifyZeroKnowledge => write!(f, "verify_zero_knowledge"),
            SecurityAnnotation::PowerResistant => write!(f, "power_resistant"),
        }
    }
}

/// Security-annotated item
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SecurityAnnotated<T> {
    pub annotations: Vec<SecurityAnnotation>,
    pub item: T,
}

/// Module configuration
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModuleConfig {
    pub default_crypto_provider: Option<String>,
    pub post_quantum_enabled: bool,
    pub hardware_acceleration: bool,
    pub custom_settings: std::collections::HashMap<String, String>,
}

impl Default for ModuleConfig {
    fn default() -> Self {
        Self {
            default_crypto_provider: None,
            post_quantum_enabled: false,
            hardware_acceleration: false,
            custom_settings: std::collections::HashMap::new(),
        }
    }
}

/// Module definition
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Module {
    pub name: Identifier,
    pub declarations: Vec<Declaration>,
    pub config: ModuleConfig,
}

/// External library declaration
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ExternBlock {
    pub library_path: String,
    pub alias: Option<Identifier>,
    pub functions: Vec<ExternFunction>,
}

/// External function declaration
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ExternFunction {
    pub name: Identifier,
    pub parameters: Vec<Parameter>,
    pub return_type: Option<Type>,
}

/// Function parameter
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Parameter {
    pub name: Identifier,
    pub typ: Type,
    pub mutable: bool,
    pub reference: bool,
}

/// Struct field
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StructField {
    pub name: Identifier,
    pub typ: Type,
    pub public: bool,
}

/// Enum variant
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EnumVariant {
    pub name: Identifier,
    pub fields: Option<Vec<Type>>,
}

/// Trait item (function or constant)
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum TraitItem {
    Function(Function),
    Constant(Constant),
    TypeAlias(TypeAlias),
}

/// Implementation item
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ImplItem {
    Function(Function),
    Constant(Constant),
    TypeAlias(TypeAlias),
}

/// Type alias
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TypeAlias {
    pub name: Identifier,
    pub generics: Vec<GenericParam>,
    pub target: Type,
    pub where_clause: Option<Vec<WhereClauseItem>>,
}

/// Generic parameter
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GenericParam {
    pub name: Identifier,
    pub bounds: Vec<GenericBound>,
}

/// Generic bound
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum GenericBound {
    Type(Type),
    Lifetime(String),
    Trait(String),
}

/// Where clause item
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WhereClauseItem {
    pub param: GenericParam,
    pub bounds: Vec<GenericBound>,
}

/// Constant declaration
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Constant {
    pub name: Identifier,
    pub typ: Type,
    pub value: Expression,
}

/// Static variable declaration
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StaticVariable {
    pub name: Identifier,
    pub typ: Type,
    pub mutable: bool,
    pub value: Expression,
}

/// Pattern matching
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Pattern {
    Literal(Literal),
    Identifier {
        name: Identifier,
        mutable: bool,
        reference: bool,
        subpattern: Option<Box<Pattern>>,
    },
    Wildcard,
    Reference {
        mutable: bool,
        pattern: Box<Pattern>,
    },
    Struct {
        typ: Type,
        fields: Vec<FieldPattern>,
    },
    Enum {
        typ: Type,
        variant: Identifier,
        fields: Option<Vec<Pattern>>,
    },
    Tuple(Vec<Pattern>),
    Array(Vec<Pattern>),
    Range {
        start: Box<Expression>,
        end: Option<Box<Expression>>,
    },
}

/// Field pattern in struct patterns
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FieldPattern {
    pub name: Identifier,
    pub pattern: Pattern,
}

/// Literal values
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Literal {
    Integer(String),
    Float(String),
    String(String),
    ByteString(Vec<u8>),
    Char(char),
    Bool(bool),
}

/// Binary operator
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BinaryOp {
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    BitAnd,
    BitOr,
    BitXor,
    Shl,
    Shr,
    Eq,
    Ne,
    Lt,
    Gt,
    Le,
    Ge,
    And,
    Or,
}

/// Unary operator
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UnaryOp {
    Neg,
    Not,
    Deref,
    Borrow,
    BorrowMut,
}

/// Main AST node types (these would be generated by ANTLR)
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Declaration {
    Module(Module),
    Import {
        path: String,
        alias: Option<Identifier>,
    },
    Function(Function),
    Struct {
        name: Identifier,
        generics: Vec<GenericParam>,
        fields: Option<Vec<StructField>>,
        where_clause: Option<Vec<WhereClauseItem>>,
    },
    Enum {
        name: Identifier,
        generics: Vec<GenericParam>,
        variants: Vec<EnumVariant>,
        where_clause: Option<Vec<WhereClauseItem>>,
    },
    Trait {
        name: Identifier,
        generics: Vec<GenericParam>,
        items: Vec<TraitItem>,
        where_clause: Option<Vec<WhereClauseItem>>,
    },
    Impl {
        generics: Vec<GenericParam>,
        trait_type: Option<Type>,
        impl_type: Type,
        items: Vec<ImplItem>,
        where_clause: Option<Vec<WhereClauseItem>>,
    },
    TypeAlias(TypeAlias),
    Constant(Constant),
    Static(StaticVariable),
    Config(ModuleConfig),
    Extern(ExternBlock),
}

/// Function definition
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Function {
    pub name: Identifier,
    pub generics: Vec<GenericParam>,
    pub parameters: Vec<Parameter>,
    pub return_type: Option<Type>,
    pub body: Option<Vec<Statement>>,
    pub where_clause: Option<Vec<WhereClauseItem>>,
    pub security_annotations: Vec<SecurityAnnotation>,
}

/// Statement types
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Statement {
    Let {
        pattern: Pattern,
        typ: Option<Type>,
        value: Option<Expression>,
    },
    Expression(Expression),
    Assignment {
        target: Expression,
        value: Expression,
    },
    Return(Option<Expression>),
    Break(Option<Expression>),
    Continue,
    If {
        condition: Expression,
        then_block: Vec<Statement>,
        else_ifs: Vec<(Expression, Vec<Statement>)>,
        else_block: Option<Vec<Statement>>,
    },
    Match {
        expression: Expression,
        arms: Vec<MatchArm>,
    },
    While {
        condition: Expression,
        body: Vec<Statement>,
    },
    For {
        pattern: Pattern,
        iterator: Expression,
        body: Vec<Statement>,
    },
    Loop {
        body: Vec<Statement>,
    },
}

/// Match arm
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MatchArm {
    pub pattern: Pattern,
    pub guard: Option<Expression>,
    pub body: Expression,
}

/// Expression types
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Expression {
    Literal(Literal),
    Variable(Identifier),
    Binary {
        left: Box<Expression>,
        op: BinaryOp,
        right: Box<Expression>,
    },
    Unary {
        op: UnaryOp,
        expression: Box<Expression>,
    },
    Call {
        function: Box<Expression>,
        args: Vec<Expression>,
    },
    Index {
        array: Box<Expression>,
        index: Box<Expression>,
    },
    Field {
        object: Box<Expression>,
        field: Identifier,
    },
    Method {
        object: Box<Expression>,
        method: Identifier,
        args: Vec<Expression>,
    },
    Tuple(Vec<Expression>),
    Array(Vec<Expression>),
    Struct {
        typ: Type,
        fields: Vec<(Identifier, Expression)>,
    },
    Enum {
        typ: Type,
        variant: Identifier,
        fields: Option<Vec<Expression>>,
    },
    Range {
        start: Box<Expression>,
        end: Option<Box<Expression>>,
    },
    Reference {
        mutable: bool,
        expression: Box<Expression>,
    },
    Dereference(Box<Expression>),
    TypeCast {
        expression: Box<Expression>,
        typ: Type,
    },
    Grouped(Box<Expression>),
    Block {
        statements: Vec<Statement>,
        expression: Option<Box<Expression>>,
    },
    If {
        condition: Box<Expression>,
        then_block: Box<Expression>,
        else_ifs: Vec<(Expression, Expression)>,
        else_block: Option<Box<Expression>>,
    },
    Match {
        expression: Box<Expression>,
        arms: Vec<MatchArm>,
    },
    Closure {
        params: Vec<Parameter>,
        return_type: Option<Type>,
        body: Box<Expression>,
    },
    Async {
        body: Box<Expression>,
    },
    Await(Box<Expression>),

    // Cryptographic expressions
    Encrypt {
        data: Box<Expression>,
        key: Box<Expression>,
    },
    Decrypt {
        data: Box<Expression>,
        key: Box<Expression>,
    },
    Sign {
        message: Box<Expression>,
        key: Box<Expression>,
    },
    Verify {
        message: Box<Expression>,
        signature: Box<Expression>,
        key: Box<Expression>,
    },
    KeyGen(AlgorithmType),
    Kem(Box<Expression>),
    Proof {
        typ: Type,
        statement: Box<Expression>,
        witness: Box<Expression>,
    },
    VerifyProof {
        statement: Box<Expression>,
        proof: Box<Expression>,
    },
}

/// Error types for the T4 language
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ErrorType {
    CryptoError,
    InvalidKey,
    DecryptionFailed,
    AuthenticationFailed,
    WeakParameter,
    HardwareFailure,
    TimingAttackDetected,
    Custom(String),
}

impl fmt::Display for ErrorType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ErrorType::CryptoError => write!(f, "CryptoError"),
            ErrorType::InvalidKey => write!(f, "InvalidKey"),
            ErrorType::DecryptionFailed => write!(f, "DecryptionFailed"),
            ErrorType::AuthenticationFailed => write!(f, "AuthenticationFailed"),
            ErrorType::WeakParameter => write!(f, "WeakParameter"),
            ErrorType::HardwareFailure => write!(f, "HardwareFailure"),
            ErrorType::TimingAttackDetected => write!(f, "TimingAttackDetected"),
            ErrorType::Custom(s) => write!(f, "{}", s),
        }
    }
}

/// Result type for cryptographic operations
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ResultType {
    pub success_type: Type,
    pub error_type: ErrorType,
}

/// Program representation
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Program {
    pub declarations: Vec<Declaration>,
    pub config: ModuleConfig,
}

/// AST visitor trait for traversing and transforming the AST
pub trait AstVisitor<T> {
    fn visit_program(&mut self, program: &Program) -> T;
    fn visit_declaration(&mut self, decl: &Declaration) -> T;
    fn visit_expression(&mut self, expr: &Expression) -> T;
    fn visit_statement(&mut self, stmt: &Statement) -> T;
    fn visit_type(&mut self, typ: &Type) -> T;
    fn visit_pattern(&mut self, pattern: &Pattern) -> T;
}

/// Default implementation of AST visitor
pub struct DefaultVisitor;

impl AstVisitor<()> for DefaultVisitor {
    fn visit_program(&mut self, _program: &Program) -> () {
        // Default implementation does nothing
    }

    fn visit_declaration(&mut self, _decl: &Declaration) -> () {
        // Default implementation does nothing
    }

    fn visit_expression(&mut self, _expr: &Expression) -> () {
        // Default implementation does nothing
    }

    fn visit_statement(&mut self, _stmt: &Statement) -> () {
        // Default implementation does nothing
    }

    fn visit_type(&mut self, _typ: &Type) -> () {
        // Default implementation does nothing
    }

    fn visit_pattern(&mut self, _pattern: &Pattern) -> () {
        // Default implementation does nothing
    }
}